#!/bin/bash
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running
puppet resource file /21051201/clone ensure=absent force=true
puppet resource file /21051201 ensure=directory
puppet resource file /21051201/clone ensure=directory
cd /21051201/clone
https://git@github.com:hdyhr/operate_repo.git
git clone https://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@github.com/bcsim-git/devops_repo.git
cp -p /21051201/clone/operate_repo/index.html /var/www/html

